#!/usr/bin/env python3

import sys
import os
import subprocess

os.environ["LD_PRELOAD"] = "./sandbox.so"
os.environ['BASE_DIR'] = "./"

command = []

idx = 1
argc = len(sys.argv)
while idx < argc:
    s = sys.argv[idx]
    if s.startswith("-"):
        if s == "--":
            command += sys.argv[idx+1:]
            break
        elif s == "-d" and idx + 1 < argc:
            os.environ['BASE_DIR'] = sys.argv[idx+1]
            idx += 1
        elif s == "-p" and idx + 1 < argc:
            os.environ["LD_PRELOAD"] = sys.argv[idx+1]
            idx += 1
        else:
            print("./sandbox: invalid option -- '{}'".format(s[1:]))
            print("usage: ./sandbox [-p sopath] [-d basedir] [--] cmd [cmd args ...]")
            print("        -p: set the path to sandbox.so, default = ./sandbox.so")
            print("        -d: the base directory that is allowed to access, default = .")
            print("        --: seperate the arguments for sandbox and for the executed command")
            exit(1)
    else:
        command.append(s)
    idx += 1

if len(command) == 0:
    print("no command given.")
    exit(1)

subprocess.run(command, env=os.environ)
